# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#target-branch
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: "daily"
    labels:
      - 'Type: Dependency'
    commit-message:
      prefix: 'chore'
      include: "scope"
    target-branch: 'master'

  - package-ecosystem: 'npm'
    directory: '/template/static'
    schedule:
      interval: "daily"
    labels:
      - 'Type: Dependency'
    commit-message:
      prefix: 'chore'
      include: "scope"
    target-branch: 'master'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: "daily"
    labels:
      - 'Type: Dependency'
    commit-message:
      prefix: 'chore'
      include: "scope"
    target-branch: 'master'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
